name: Docker Image CI
on:
  push:
    branches: master

env:
    TAG: ${{ github.ref }}

jobs:
  docker_build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v1

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
          with:
            platforms: all

        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v1

        - name: Cache Docker layers
          uses: actions/cache@v2
          with:
            path: /tmp/.buildx-cache
            key: ${{ runner.os }}-buildx-${{ github.sha }}
            restore-keys: |
              ${{ runner.os }}-buildx-
          
        - name: Login to DockerHub
          if: github.event_name == 'pull_request'
          uses: docker/login-action@v1 
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
                    
        - id: docker-tag
          uses: yuya-takeyama/docker-tag-from-github-ref-action@v1
                    
        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            builder: ${{ steps.buildx.outputs.name }}
            context: .
            file: ./Dockerfile
            platforms: linux/amd64 #,linux/386,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x
            push: ${{ github.event_name != 'pull_request' }}
            tags: qwertycoin/qwertycoin:${{ steps.docker-tag.outputs.tag }}
            cache-from: type=local,src=/tmp/.buildx-cache
            cache-to: type=local,dest=/tmp/.buildx-cache

        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}
